export const C = {
  bg: "#0B0D14",
  surface: "#111520",
  card: "#161929",
  cardAlt: "#13161f",
  row: "#12151f",
  rowHov: "#1a1e2c",
  border: "rgba(255,255,255,0.07)",
  borderSoft: "rgba(255,255,255,0.04)",
  text: "#E3E8F3",
  sub: "rgba(227,232,243,0.75)",
  muted: "#64748B",
  blue: "#0a81d1",
  blueDim: "rgba(10,129,209,0.12)",
  green: "#4cbc9a",
  greenDim: "rgba(76,188,154,0.12)",
  amber: "#FBBF24",
  amberDim: "rgba(251,191,36,0.1)",
  red: "#fe4040",
  redDim: "rgba(254,64,64,0.12)",
  orange: "#FF793F",
  orangeDim: "rgba(255,121,63,0.12)",
  purple: "#CBD5E1",
  purpleDim: "rgba(255,255,255,0.06)",
};

export const PENDING_RECORDS = [
  {
    id: "p1",
    name: "Ravi Kumar",
    class: "10",
    section: "A",
    parentFullName: "Sanjay Kumar",
    dob: "15/05/2004",
    gender: "Male",
    requestDate: "05/04/2026",
    reason: "Parent Transfer",
    status: "Pending Approval",
  },
  {
    id: "p2",
    name: "Anita Sharma",
    class: "9",
    section: "B",
    parentFullName: "Rajesh Sharma",
    dob: "22/08/2005",
    gender: "Female",
    requestDate: "06/04/2026",
    reason: "Admission Elsewhere",
    status: "In Process",
  },
  {
    id: "p3",
    name: "Karan Singh",
    class: "8",
    section: "C",
    parentFullName: "Amar Singh",
    dob: "10/11/2006",
    gender: "Male",
    requestDate: "04/04/2026",
    reason: "Personal Reasons",
    status: "Pending Approval",
  },
  {
    id: "p4",
    name: "Meera Reddy",
    class: "10",
    section: "B",
    parentFullName: "Vishal Reddy",
    dob: "09/09/2004",
    gender: "Female",
    requestDate: "07/04/2026",
    reason: "Health Issues",
    status: "Pending Approval",
  },
];

export const ALUMNI_RECORDS = [
  {
    id: "a1",
    name: "Sunita Verma",
    class: "10",
    section: "A",
    parentFullName: "Mohan Verma",
    dob: "12/04/2004",
    gender: "Female",
    tcNumber: "TC-2024-0012",
    tcDate: "15/03/2024",
    reason: "Parent Transfer",
    conduct: "Excellent",
    promoStatus: "Promoted",
    feeStatus: "All Paid",
  },
  {
    id: "a2",
    name: "Rajiv Kapoor",
    class: "10",
    section: "B",
    parentFullName: "Suresh Kapoor",
    dob: "08/07/2004",
    gender: "Male",
    tcNumber: "TC-2024-0013",
    tcDate: "16/03/2024",
    reason: "Admission Elsewhere",
    conduct: "Good",
    promoStatus: "Promoted",
    feeStatus: "All Paid",
  },
  {
    id: "a3",
    name: "Kavya Reddy",
    class: "10",
    section: "A",
    parentFullName: "Krishna Reddy",
    dob: "30/09/2003",
    gender: "Female",
    tcNumber: "TC-2023-0087",
    tcDate: "22/11/2023",
    reason: "Job Transfer",
    conduct: "Excellent",
    promoStatus: "Passed Out",
    feeStatus: "All Paid",
  },
  {
    id: "a4",
    name: "Mohd. Irfan",
    class: "9",
    section: "B",
    parentFullName: "Abdul Rehman",
    dob: "14/02/2005",
    gender: "Male",
    tcNumber: "TC-2024-0028",
    tcDate: "05/05/2024",
    reason: "Health Issues",
    conduct: "Good",
    promoStatus: "Not Promoted",
    feeStatus: "Fees Waived",
  },
  {
    id: "a5",
    name: "Pooja Menon",
    class: "10",
    section: "A",
    parentFullName: "Rajan Menon",
    dob: "27/06/2003",
    gender: "Female",
    tcNumber: "TC-2023-0054",
    tcDate: "10/07/2023",
    reason: "Admission Elsewhere",
    conduct: "Excellent",
    promoStatus: "Passed Out",
    feeStatus: "All Paid",
  },
  {
    id: "a6",
    name: "Vikram Shetty",
    class: "8",
    section: "B",
    parentFullName: "Dilip Shetty",
    dob: "03/11/2004",
    gender: "Male",
    tcNumber: "TC-2024-0041",
    tcDate: "30/06/2024",
    reason: "Personal Reasons",
    conduct: "Satisfactory",
    promoStatus: "Promoted",
    feeStatus: "All Paid",
  },
  {
    id: "a7",
    name: "Aisha Siddiqui",
    class: "9",
    section: "A",
    parentFullName: "Zubair Siddiqui",
    dob: "20/08/2006",
    gender: "Female",
    tcNumber: "TC-2024-0056",
    tcDate: "15/07/2024",
    reason: "Parent Transfer",
    conduct: "Good",
    promoStatus: "Promoted",
    feeStatus: "All Paid",
  },
  {
    id: "a8",
    name: "Hardik Patel",
    class: "10",
    section: "B",
    parentFullName: "Ramesh Patel",
    dob: "17/01/2005",
    gender: "Male",
    tcNumber: "TC-2023-0099",
    tcDate: "28/09/2023",
    reason: "Admission Elsewhere",
    conduct: "Excellent",
    promoStatus: "Passed Out",
    feeStatus: "All Paid",
  },
  {
    id: "a9",
    name: "Shruti Iyer",
    class: "10",
    section: "A",
    parentFullName: "Venkat Iyer",
    dob: "05/03/2004",
    gender: "Female",
    tcNumber: "TC-2024-0018",
    tcDate: "20/04/2024",
    reason: "Parent Transfer",
    conduct: "Excellent",
    promoStatus: "Promoted",
    feeStatus: "Fees Due",
  },
  {
    id: "a10",
    name: "Nikhil Bose",
    class: "7",
    section: "A",
    parentFullName: "Amit Bose",
    dob: "11/10/2006",
    gender: "Male",
    tcNumber: "TC-2024-0067",
    tcDate: "08/08/2024",
    reason: "Job Transfer",
    conduct: "Good",
    promoStatus: "Promoted",
    feeStatus: "All Paid",
  },
  {
    id: "a11",
    name: "Divya Krishnamurthy",
    class: "10",
    section: "B",
    parentFullName: "Suresh Krishnamurthy",
    dob: "22/12/2002",
    gender: "Female",
    tcNumber: "TC-2023-0031",
    tcDate: "15/06/2023",
    reason: "Admission Elsewhere",
    conduct: "Excellent",
    promoStatus: "Passed Out",
    feeStatus: "All Paid",
  },
  {
    id: "a12",
    name: "Aman Chauhan",
    class: "9",
    section: "B",
    parentFullName: "Rajinder Chauhan",
    dob: "09/05/2005",
    gender: "Male",
    tcNumber: "TC-2024-0073",
    tcDate: "12/09/2024",
    reason: "Health Issues",
    conduct: "Satisfactory",
    promoStatus: "Detained",
    feeStatus: "Fees Waived",
  },
];

export const CLASSES = ["All", "6", "7", "8", "9", "10"];
export const SECTIONS = ["All", "A", "B", "C"];

export const DEFAULT_CHECKLIST = [
  { id: "noc", label: "NOC (No Objection Certificate)", checked: false, isDefault: true },
  { id: "dues", label: "Dues Clearance", checked: false, isDefault: true },
];

export const TC_REASON_OPTIONS = [
  "Parent Transfer",
  "Job Transfer",
  "Admission Elsewhere",
  "Health Issues",
  "Personal Reasons",
  "Others",
];

export const TC_CONDUCT_OPTIONS = ["Excellent", "Good", "Satisfactory", "Poor"];

export const TC_PROMOTION_OPTIONS = ["Promoted", "Not Promoted", "Detained", "Passed Out"];

export const CERTIFICATE_SIGNERS = ["Principal", "Class Teacher", "Accounts", "Parent/Guardian"];

export const TH = {
  padding: "11px 18px",
  fontSize: "11px",
  fontWeight: 700,
  color: C.muted,
  textTransform: "uppercase",
  letterSpacing: "0.06em",
  textAlign: "left",
  borderBottom: `1px solid ${C.border}`,
  background: "#0d1017",
  whiteSpace: "nowrap",
};

export const PAGE_TRANSITION = {
  duration: 0.22,
  ease: [0.22, 1, 0.36, 1],
};
